use_frameworks!

platform :ios, '9.0'

target 'GMURLRouter_Example' do
  pod 'GMURLRouter', :path => '../'

  target 'GMURLRouter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
